### ISSUE TITLE
How to use Thumbnail Generation from Cognitive service in Azure function using C#

### ISSUE THREAD

**Issue by chandra-shekar-y** [joshdcar/azure-functions-extensions-cognitive-services#1]
Hi All,

I have written the sample console application that would generate thumbnail from the existing image. But, I would like to generate thumbnail image that comes through a request. i.e.  Below is the flow of generating thumb nails which is not working.

1. I have a Http triggered azure function that would save the images to blob.
2. Now, before saving to blob I would like the azure function to generate thumb nails of the image and then save both the original and thumb images to blob.

I am getting "**InvalidImageFormat**" error while generating the thumb. The same is working on the console based application.

Any help is appreciated.

Thanks,
Chandra

**Comment by joshdcar** [comment]
Hi @chandra-shekar-y  - Your use case is pretty straight forward. I am working on dedicated documentation for the project that would likely make it more clear on what you need to do but in the mean time I'll put together a few code snippets for you this evening and get back to you. 

In regards to the InvalidImageFormat exception there is some new validation going on in the latest release. We're using file headers to identify if the file type and image format is supported (e.g. bitmap, jpg, etc).  This is more reliable then simply looking at the extension.  It came out of a recent experience where files were being misnamed (e.g. from pdf to jpg) so we had the correct extension but the file was not valid.  Anyway I'm using the common file signatures to validate (https://en.wikipedia.org/wiki/List_of_file_signatures) . It's possible that needs some tweaking or your image format is not supported by cognitive services (e.g. jpg, gif, png, bmp). If you're able to share the file you were trying to process that would go along way to help me resolve that for you.

**Comment by joshdcar** [comment]
Hi @chandra-shekar-y  

In the process of putting together some code for you I discovered a couple issues unrelated to your request with my recent release a couple days ago so  **Please pull down the latest Preview3 from Nuget** before going any further.  

Don't forget to have your VisionUrl, VisionKey, and the StorageAccount all in your appsettings and of course update the paths to the blobs as appropriate. 

```

[StorageAccount("StorageAccount")]
[FunctionName("ThumbnailGenApi")]
public static async Task<IActionResult> ThumbnailGenApi(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "generatethumbnail/{filename}")]HttpRequest req,
            [Blob("images/{filename}", FileAccess.Write)]Stream imageStream,
            [Blob("thumbnails/{filename}", FileAccess.Write)]Stream thumbnailImageStream,
            [VisionThumbnail(SmartCropping = true, Height = "150", Width = "150")]VisionThumbnailClient client,
            string fileName,
            TraceWriter log)
        {

            //Load Http Request Body into Thumbnail Request
            var request = new VisionThumbnailRequest(req.Body);

            //Generate Thumbnail
            var thumbnailBytes = await client.ThumbnailAsync(request);

            //Output Original Image to Blob Storage
            using (MemoryStream stream = new MemoryStream(request.ImageBytes))
            {
                await stream.CopyToAsync(imageStream);
            }

            //Output Thumbnail To Blob Storage
            using (MemoryStream stream = new MemoryStream(thumbnailBytes))
            {
                await stream.CopyToAsync(thumbnailImageStream);
            }
          
            return (ActionResult)new OkResult();

        }

```

In regards to the InvalidImageSource some quick testing with some various images I use for testing have all been successful.  If you are sure you have a valid image and you don't mind sharing the file I can take a look at it and make sure I'm covering whatever use case we're hitting for your image file.  Alternatively I can give you some guidance on how to find out the first bits of the file and you can share those with me and I can check the header of your file.

I'll keep this issue open for the time being due to the InvalidImageSource.

**Comment by chandra-shekar-y** [comment]
Hi @joshdcar,

Thank you for the solution. But, would you please provide the solution without updating/pulling down the latest preview.

Thanks,
Chandra

**Comment by joshdcar** [comment]
@chandra-shekar-y  Your welcome. That code snippet would be the same for the previous version (Preview2) as well.  The fixes were all behind the scenes. Saying that I would still encourage you to pull the latest version of the nuget package  for your project.

Cheers,

Josh

**Comment by chandra-shekar-y** [comment]
Thank you for the support.
